
universe              = vanilla
notification          = Never 
nice_user             = True
getenv                = True
request_cpus          = 1

request_memory        = 2000 
should_transfer_files = no


executable = /extra/scratch03/jantoran/anaconda2/bin/python
arguments  = run1_train_hmm.py
output     = .condor/run1_train_hmm.log
error      = .condor/run1_train_hmm.err
log        = .condor/run1_train_hmm.clog
queue

